[random]
quotes = [
	"...",
	"Bruh..",
	"Duh.",
	"Ok.",
	"-_-",
]

[capture] # when opponent captures
pawn = [
	"ok.",
	"sigh.",
	"..",
	"...",
	".",
]

knight = [
	"knight.",
	"ok.",
	"hmm",
	".",
	"uhh",
]

bishop = [
	"uh",
	"oh",
	"hmm.",
	"yeah.",
	"-.-",
]

rook = [
	"rook",
	"ok.",
	"yeah.",
	"oh!",
	"mhm.",
]

queen = [
	"damn.",
	"argh.",
	"oh?",
	"...",
	".-.",
]

[take]
pawn = [
	"pawn",
	"...",
	".",
	"-.-",
	":_:",
]

knight = [
	"horse.",
	"..",
	"-_-",
	"-.-",
	"?_?",
]

bishop = [
	"",
	"",
	"",
	"",
	"",
]

rook = [
	"",
	"",
	"",
	"",
	"",
]

queen = [
	"",
	"",
	"",
	"",
	"",
]

rare = [
	"",
	"",
	""
]



[check] # opponent

quotes = [
	"",
	"",
	"",
	"",
	"",
]

[checked] # Ferris
quotes = [
	"",
	"",
	"",
]

[checkmate]

quotes = [
	"",
	"",
	"",
	"",
	"",
]
